#illustration of word embeddings using chat gpt

In [ ]:
from google.colab import userdata

In [ ]:
import openai

In [ ]:
import os

In [ ]:
from openai import OpenAI
client = OpenAI()

In [ ]:
def getEmbedding(text):
  response = client.embeddings.create(input=text, model="text-embedding-ada-002")
  return response.data[0].embedding

In [ ]:
mytext = "the fox crossed the road in front of me"
getEmbedding(mytext)

[-0.005632546730339527,
 0.00235806405544281,
 -0.025659725069999695,
 0.0008556359098292887,
 -0.008291407488286495,
 0.029574766755104065,
 -0.017842112109065056,
 -0.018016668036580086,
 0.009687855839729309,
 -0.021457914263010025,
 0.027604777365922928,
 0.01403928641229868,
 0.023714672774076462,
 -0.01897672563791275,
 0.008347515016794205,
 0.0030188828241080046,
 0.02381441928446293,
 0.0020042764954268932,
 0.01610902138054371,
 -0.022505249828100204,
 -0.016844648867845535,
 0.03665675222873688,
 0.00756201334297657,
 -0.025535043329000473,
 -0.014849724248051643,
 0.004223630763590336,
 0.013178974390029907,
 -0.015111558139324188,
 -0.0045072841458022594,
 -0.004853278864175081,
 7.515062316088006e-05,
 -0.005819570738822222,
 -0.024275746196508408,
 0.0007317323470488191,
 -0.012592965736985207,
 -0.01774236559867859,
 -0.00021897420811001211,
 -0.014899597503244877,
 0.007044579833745956,
 -0.02287929877638817,
 0.012536858208477497,
 0.008391153998672962,
 -0.017206229269504547,
 -0.010336206294596195,
 -0.0030578463338315487,
 0.01962507702410221,
 -0.00464131822809577,
 0.002588727278634906,
 -0.027804270386695862,
 0.02645769529044628,
 -0.003593982430174947,
 -0.00661442382261157,
 -0.015198836103081703,
 -0.020348237827420235,
 -0.006237258203327656,
 -0.0011190283112227917,
 0.016320981085300446,
 0.00037307440652512014,
 0.008771437220275402,
 0.0021242836955934763,
 -0.019861973822116852,
 0.010167884640395641,
 -0.020073935389518738,
 -0.020048998296260834,
 -0.01571003533899784,
 -0.02259252779185772,
 0.021270889788866043,
 -0.00761812087148428,
 -0.005791517440229654,
 0.015360924415290356,
 0.011427180841565132,
 0.0017081546830013394,
 -0.005679302848875523,
 -0.0031466828659176826,
 0.017704961821436882,
 0.0007710853242315352,
 -0.015722503885626793,
 0.0039119236171245575,
 0.011657844297587872,
 0.00719419913366437,
 0.022118734195828438,
 -0.05062122642993927,
 0.002950307447463274,
 0.021807026118040085,
 0.03089640475809574,
 0.008384919725358486,
 -0.025734534487128258,
 0.022854361683130264,
 -0.032143231481313705,
 0.0025185931008309126,
 0.007094452623277903,
 0.02113373950123787,
 -0.015074153430759907,
 0.006427399814128876,
 -0.003422543639317155,
 0.008073212578892708,
 -0.012979482300579548,
 0.043638989329338074,
 0.0005069136386737227,
 -0.0072877113707363605,
 0.015111558139324188,
 -0.009126782417297363,
 -0.01623370312154293,
 0.004803406074643135,
 -0.03625776618719101,
 -0.028452621772885323,
 -0.004201811272650957,
 0.030173243954777718,
 -0.006882491987198591,
 -0.01857774145901203,
 -0.001282674609683454,
 0.01629604585468769,
 0.02062254026532173,
 -0.025298144668340683,
 -0.027480095624923706,
 -0.014051754027605057,
 0.005919317249208689,
 0.0064461021684110165,
 -0.013889666646718979,
 0.0020042764954268932,
 0.020098870620131493,
 0.029125908389687538,
 -0.0008088798495009542,
 -0.006252843886613846,
 -0.006745340768247843,
 0.011140410788357258,
 -0.00522421021014452,
 -0.008422324433922768,
 -0.0015226890100166202,
 0.019712354987859726,
 0.02124595269560814,
 -0.004089596681296825,
 0.04752909392118454,
 0.0033227973617613316,
 -0.022642401978373528,
 0.02585921809077263,
 -0.013428340665996075,
 0.006427399814128876,
 -0.010217757895588875,
 -0.021333230659365654,
 0.0034942361526191235,
 0.018602678552269936,
 -0.0021554543636739254,
 -0.002319100545719266,
 0.015223773196339607,
 0.04074634611606598,
 0.018939321860671043,
 -0.005679302848875523,
 0.023627394810318947,
 -0.01973729208111763,
 0.02645769529044628,
 -0.028352875262498856,
 0.038751423358917236,
 0.0016910107806324959,
 -0.0026370417326688766,
 0.025435296818614006,
 -2.0394896637299098e-05,
 0.025136057287454605,
 -0.023191004991531372,
 -0.005803985521197319,
 0.009637982584536076,
 0.023714672774076462,
 0.013565491884946823,
 -0.01821616105735302,
 -0.012106702663004398,
 0.02807857282459736,
 0.028577303513884544,
 0.009619279764592648,
 -0.015635225921869278,
 0.004544688854366541,
 0.010548166930675507,
 0.017268572002649307,
 -0.013540554791688919,
 0.01775483414530754,
 0.009332509711384773,
 -0.003447480034083128,
 0.011314966715872288,
 0.005355127155780792,
 -0.022218478843569756,
 0.008185427635908127,
 -0.031843993812799454,
 0.019874442368745804,
 0.042018111795186996,
 0.0019808984361588955,
 -0.008628051728010178,
 0.014163969084620476,
 0.0015086622443050146,
 -0.02797882631421089,
 -0.013702642172574997,
 -0.007611886598169804,
 0.00933874398469925,
 0.011495756916701794,
 0.005233561620116234,
 -0.01908894069492817,
 -0.6918400526046753,
 -0.02346530742943287,
 0.010255162604153156,
 -0.003456831444054842,
 0.021994050592184067,
 0.04057179018855095,
 -0.006907428614795208,
 -0.008684159256517887,
 -0.014513080939650536,
 0.011689014732837677,
 -0.029973750934004784,
 -0.005267849192023277,
 0.02270474284887314,
 -0.006006595212966204,
 -0.017966795712709427,
 -0.015784846618771553,
 0.025584915652871132,
 -0.00910808052867651,
 -0.004027255345135927,
 0.0012000722344964743,
 -0.007106921169906855,
 0.0005665275966748595,
 -0.01527364645153284,
 -0.00849090050905943,
 0.023502713069319725,
 0.006090756040066481,
 0.0020292128901928663,
 -0.007936062291264534,
 0.00333526567555964,
 0.007063282188028097,
 -0.02213120087981224,
 0.01494947075843811,
 -0.009326275438070297,
 0.017318444326519966,
 0.05186805501580238,
 -0.02650756947696209,
 0.01030503585934639,
 0.030696911737322807,
 0.017642619088292122,
 0.04214279353618622,
 -0.015011812560260296,
 0.0002620287414174527,
 0.00439195241779089,
 -0.004045957699418068,
 -0.010915981605648994,
 -0.011626673862338066,
 0.026532504707574844,
 0.0031716194935142994,
 0.00817919336259365,
 -0.014263715595006943,
 -0.003603333607316017,
 0.011252624914050102,
 -0.0001784522901289165,
 0.011258859187364578,
 -0.02208132855594158,
 0.020285895094275475,
 0.03082159534096718,
 0.0022240299731492996,
 0.009344978258013725,
 0.013203911483287811,
 -0.006477272603660822,
 0.0012273465981706977,
 -0.005090176593512297,
 -0.0009460309520363808,
 -0.003572162939235568,
 -0.00975019671022892,
 0.007013408932834864,
 -0.003721782239153981,
 0.029175780713558197,
 -0.006075170822441578,
 0.014687636867165565,
 0.027056172490119934,
 -0.018727360293269157,
 0.009207827039062977,
 0.023951571434736252,
 0.009719026274979115,
 -0.007742803543806076,
 -0.013303657062351704,
 -0.0028786147013306618,
 0.006589487195014954,
 0.017418190836906433,
 -0.00369372870773077,
 -0.016495537012815475,
 0.00223338115029037,
 0.01442580297589302,
 0.009027036838233471,
 -0.017206229269504547,
 0.01001826487481594,
 -1.9025089841306908e-06,
 -0.014712573029100895,
 0.009613045491278172,
 0.018590210005640984,
 -0.00858441274613142,
 -0.00843479298055172,
 0.018939321860671043,
 0.012038126587867737,
 -0.007929828017950058,
 0.033664364367723465,
 0.035759035497903824,
 -0.008684159256517887,
 0.010591805912554264,
 -0.00021351933537516743,
 0.005205507855862379,
 -0.019899379462003708,
 0.03830256313085556,
 0.013303657062351704,
 0.009687855839729309,
 0.008322578854858875,
 0.008833778090775013,
 -0.02860224060714245,
 -0.008416091091930866,
 0.0059317853301763535,
 0.012175277806818485,
 -0.0019808984361588955,
 0.001603732816874981,
 -0.02218107506632805,
 0.01369017455726862,
 -0.011015728116035461,
 0.011807464063167572,
 -0.023677268996834755,
 0.016009274870157242,
 -0.004781586583703756,
 0.0172186978161335,
 -0.015211304649710655,
 0.016844648867845535,
 0.014575422741472721,
 -0.0050153667107224464,
 -0.003656323766335845,
 -0.013266252353787422,
 -0.004089596681296825,
 0.004638201091438532,
 0.0008579737041145563,
 0.025148525834083557,
 -0.012755053117871284,
 -0.002018303144723177,
 -0.008135554380714893,
 0.014089159667491913,
 0.016146425157785416,
 0.01680724509060383,
 -0.025983901694417,
 -0.051419198513031006,
 0.011826165951788425,
 -0.012137873098254204,
 -0.011021961458027363,
 -0.003986733499914408,
 -0.024026380851864815,
 -0.007586949970573187,
 0.004638201091438532,
 -0.0069510675966739655,
 0.017592746764421463,
 0.006527145858854055,
 -0.035235367715358734,
 -0.01792939007282257,
 0.0027196442242711782,
 0.0029066684655845165,
 -0.0010247370228171349,
 -0.0037934749852865934,
 -0.007069515995681286,
 -0.0028380928561091423,
 -0.02084696851670742,
 0.014375929720699787,
 0.0072690085507929325,
 -0.002912902506068349,
 -0.0172186978161335,
 0.017206229269504547,
 -0.02002406120300293,
 0.0059442538768053055,
 0.0344623327255249,
 -0.021283358335494995,
 -0.04396316409111023,
 0.0014564512530341744,
 -0.004896917846053839,
 -0.011408478952944279,
 -0.006162448786199093,
 -0.012555561028420925,
 -0.0027134099509567022,
 0.004706776700913906,
 -0.015261177904903889,
 -0.00864052027463913,
 -0.010579337365925312,
 0.0012179953046143055,
 0.012580497190356255,
 -0.0008556359098292887,
 -0.006215438712388277,
 0.028303001075983047,
 -0.012405941262841225,
 0.009613045491278172,
 0.03112083300948143,
 -0.016383323818445206,
 0.011184049770236015,
 0.013004418462514877,
 0.012929609045386314,
 0.002806922188028693,
 0.009039504453539848,
 -0.010367376729846,
 -0.009301339276134968,
 0.013727579265832901,
 0.028452621772885323,
 0.007942295633256435,
 0.025958964601159096,
 0.017555341124534607,
 -0.014014349319040775,
 0.016857117414474487,
 -0.031320326030254364,
 0.016794776543974876,
 -0.031095895916223526,
 0.002111815381795168,
 -0.033539678901433945,
 -0.006707936059683561,
 0.007711632642894983,
 -0.005442405119538307,
 -0.01594693399965763,
 -0.007106921169906855,
 -0.036931052803993225,
 0.008191661909222603,
 0.018652550876140594,
 -0.003955562599003315,
 0.006483506876975298,
 0.0068700239062309265,
 -0.017069078981876373,
 -0.024387961253523827,
 -0.006527145858854055,
 0.0009327834122814238,
 -0.012162809260189533,
 0.009182889945805073,
 -0.01710648462176323,
 0.008397388271987438,
 0.018702423200011253,
 0.0029347219970077276,
 -0.009856177493929863,
 -0.02440042980015278,
 0.00937614869326353,
 0.012268790043890476,
 0.024088721722364426,
 -0.012050595134496689,
 -0.0019388179061934352,
 0.007724101189523935,
 -0.01915128156542778,
 0.027804270386695862,
 -0.012892204336822033,
 0.007923593744635582,
 0.0009055090486072004,
 0.025136057287454605,
 -0.013740047812461853,
 -0.006564550567418337,
 0.008403622545301914,
 0.014064222574234009,
 -0.020460451021790504,
 -0.007848784327507019,
 0.011882273480296135,
 -0.004881332628428936,
 -0.007624354679137468,
 -0.016133958473801613,
 0.0014954146463423967,
 -0.004822108428925276,
 -0.02218107506632805,
 0.009912285022437572,
 0.009731494821608067,
 0.03767915070056915,
 0.026657188311219215,
 0.004276621155440807,
 -0.003625153098255396,
 0.005230444483458996,
 -0.0013348854845389724,
 0.014637763611972332,
 0.0005875678034499288,
 -0.021856900304555893,
 0.0022442908957600594,
 -0.002853678073734045,
 -0.027355412021279335,
 -0.015261177904903889,
 -0.009868646040558815,
 0.016894523054361343,
 0.009382382966578007,
 0.03872648626565933,
 0.020572666078805923,
 -0.00684508727863431,
 0.003578397212550044,
 0.02720579318702221,
 0.011420946568250656,
 -0.008091915398836136,
 -0.04234228655695915,
 -0.0023642980959266424,
 -0.008160490542650223,
 -0.01129626389592886,
 -0.018702423200011253,
 -0.004345196299254894,
 0.006926130969077349,
 0.01214410737156868,
 0.00017893934273160994,
 0.006913662888109684,
 0.012717648409307003,
 0.011458351276814938,
 0.0012600758345797658,
 0.001603732816874981,
 -0.006096990313380957,
 0.05585790425539017,
 -0.01421384233981371,
 0.01065414771437645,
 -0.03653206676244736,
 -0.006337004713714123,
 -0.0028412099927663803,
 -0.006508443504571915,
 -0.0057603465393185616,
 0.04244203492999077,
 -0.006795214023441076,
 0.0003937250003218651,
 -0.013802388682961464,
 -0.0006378305843099952,
 0.005006015300750732,
 -0.02733047492802143,
 -0.012767521664500237,
 -0.009182889945805073,
 -0.007225369568914175,
 -0.02200651913881302,
 -0.005828922148793936,
 -0.010940917767584324,
 -0.01652047410607338,
 0.044935692101716995,
 0.009656684473156929,
 -0.005638781003654003,
 -0.010417249985039234,
 -0.02837781049311161,
 -0.004656903445720673,
 0.08857467770576477,
 0.00041885636164806783,
 0.0022100030910223722,
 -0.0025762589648365974,
 0.007119389250874519,
 -0.017330912873148918,
 -0.01991184800863266,
 -0.030497418716549873,
 0.023153601214289665,
 -0.018290970474481583,
 -0.002146103186532855,
 -0.018290970474481583,
 -0.0016582815442234278,
 -0.00017816007311921567,
 0.018415654078125954,
 -0.002585610141977668,
 -0.014026817865669727,
 -0.01340340357273817,
 -0.0019512862199917436,
 -0.02620832994580269,
 -0.003946211654692888,
 -0.012000721879303455,
 0.002093113027513027,
 0.014001881703734398,
 -0.019313368946313858,
 0.005055888555943966,
 0.0013177415821701288,
 0.02382688783109188,
 0.018727360293269157,
 -0.015921996906399727,
 -0.0010894162114709616,
 -0.01092221587896347,
 -0.008148022927343845,
 -0.015036748722195625,
 0.015734972432255745,
 -0.0016878937603905797,
 -0.000159944684128277,
 0.021644938737154007,
 0.015797313302755356,
 -0.011202751658856869,
 0.023976506665349007,
 0.023153601214289665,
 0.019014131277799606,
 -0.0016302278963848948,
 0.02165740728378296,
 -0.0036469725891947746,
 0.003690611571073532,
 0.0029035513289272785,
 0.014675168320536613,
 -0.021108802407979965,
 0.03241753578186035,
 -0.0016520473873242736,
 -0.012081765569746494,
 0.015211304649710655,
 0.008540773764252663,
 0.025185931473970413,
 0.006193619221448898,
 -0.002682239282876253,
 -0.020734753459692,
 0.022667337208986282,
 -0.006118809804320335,
 -0.010647913441061974,
 0.008983397856354713,
 0.0026650954969227314,
 0.0009125224314630032,
 -0.02406378462910652,
 -0.014226310886442661,
 0.002412612782791257,
 -0.011776292696595192,
 -0.007044579833745956,
 -0.010691552422940731,
 -0.0017720547039061785,
 -0.020772159099578857,
 -0.026432758197188377,
 0.01594693399965763,
 0.02994881570339203,
 0.008709095418453217,
 0.00014377488696482033,
 0.006502209231257439,
 0.019749758765101433,
 -0.011570566333830357,
 0.002771075814962387,
 0.015784846618771553,
 0.012917140498757362,
 -0.02867705002427101,
 0.008054510690271854,
 0.003522289916872978,
 -0.002295722486451268,
 0.01044842042028904,
 0.008185427635908127,
 0.01792939007282257,
 0.010261396877467632,
 0.006489741150289774,
 -0.0063557070679962635,
 -0.004697425290942192,
 -0.0005957501125521958,
 -0.011919678188860416,
 0.03934989869594574,
 0.005099527537822723,
 0.009301339276134968,
 0.03428777679800987,
 -0.015560416504740715,
 -0.007119389250874519,
 -0.012474516406655312,
 0.008328813128173351,
 -0.006249726749956608,
 0.043938226997852325,
 -0.001352029386907816,
 -0.009407319128513336,
 -0.016320981085300446,
 0.029001224786043167,
 -0.007113155443221331,
 0.003123304806649685,
 0.0025715832598507404,
 0.021682342514395714,
 0.019400646910071373,
 0.0012140990002080798,
 0.034661825746297836,
 -0.004282854963093996,
 -0.02218107506632805,
 0.0015600938349962234,
 -0.012175277806818485,
 -0.004385718610137701,
 0.020472919568419456,
 -0.00504965428262949,
 0.02645769529044628,
 -0.0036126847844570875,
 -0.02230575680732727,
 -0.016844648867845535,
 -0.0032822752837091684,
 0.010610508732497692,
 0.010978322476148605,
 0.0018001083517447114,
 -0.007717866916209459,
 -0.03481144458055496,
 -0.007624354679137468,
 0.002269227523356676,
 0.0034755337983369827,
 -0.01885204389691353,
 -0.0010862990748137236,
 -0.034487269818782806,
 -0.025385422632098198,
 0.012006956152617931,
 -0.015049217268824577,
 0.013278720900416374,
 -0.028303001075983047,
 -0.010105542838573456,
 -0.006209204904735088,
 -0.01723116636276245,
 0.01780470833182335,
 -0.020061466842889786,
 -0.011857336387038231,
 -0.010610508732497692,
 -0.008447261527180672,
 -0.01880216971039772,
 -0.043988101184368134,
 -0.0029362805653363466,
 0.0005567867192439735,
 0.021931709721684456,
 0.021283358335494995,
 0.02673199772834778,
 -0.017368318513035774,
 0.01179499551653862,
 0.012449580244719982,
 -0.030447546392679214,
 -0.002300398191437125,
 0.007418628316372633,
 0.006212321575731039,
 -0.04229241609573364,
 0.016246171668171883,
 0.018590210005640984,
 0.02265486866235733,
 0.04191836714744568,
 0.026956427842378616,
 -0.010529465042054653,
 0.0160591471940279,
 -0.005096410401165485,
 0.006006595212966204,
 -0.005987892858684063,
 -0.0020790861453861,
 0.01962507702410221,
 -0.004560274537652731,
 0.014338525012135506,
 -0.0033446168527007103,
 -0.009644216857850552,
 -0.011570566333830357,
 0.030921339988708496,
 0.007131857797503471,
 0.0201487448066473,
 -0.004594562109559774,
 0.04184355586767197,
 -0.012486984953284264,
 -0.00852830521762371,
 -0.014924534596502781,
 0.01334106270223856,
 -0.02650756947696209,
 -0.011963317170739174,
 0.007867486216127872,
 -0.004226747900247574,
 0.02225588448345661,
 -0.0024219639599323273,
 0.003958679735660553,
 -0.011751356534659863,
 -0.0012834538938477635,
 -0.010728957131505013,
 0.0391254723072052,
 -0.0032822752837091684,
 -0.0037747726310044527,
 0.0053364248014986515,
 -0.0154731385409832,
 -0.0036781432572752237,
 -0.021270889788866043,
 0.00025696351076476276,
 -0.036282703280448914,
 0.016782307997345924,
 0.0027134099509567022,
 -0.009868646040558815,
 0.018777234479784966,
 -0.006165565922856331,
 -0.04007305949926376,
 -0.007418628316372633,
 0.0008135554380714893,
 0.00756201334297657,
 -0.00228325417265296,
 0.023864293470978737,
 2.258658605569508e-05,
 -0.022206012159585953,
 -0.030846530571579933,
 0.014687636867165565,
 0.0166326891630888,
 -0.0012865709140896797,
 -0.005102644674479961,
 0.034487269818782806,
 -0.009519534185528755,
 0.007923593744635582,
 -0.020073935389518738,
 0.017655087634921074,
 -0.016420727595686913,
 -0.033489808440208435,
 0.0204479843378067,
 0.038676612079143524,
 0.007960998453199863,
 -0.019724823534488678,
 -0.020098870620131493,
 -0.006212321575731039,
 0.02417599968612194,
 -0.03241753578186035,
 -0.012075531296432018,
 -0.007574481889605522,
 -0.033365122973918915,
 -0.032018549740314484,
 0.0129919508472085,
 -0.023340625688433647,
 0.018939321860671043,
 -0.015348455868661404,
 -0.010610508732497692,
 0.016445664688944817,
 -0.004887566901743412,
 0.0012577379820868373,
 0.01138977613300085,
 -0.01407669112086296,
 0.03381398320198059,
 -0.029624639078974724,
 -0.0016707498580217361,
 -0.001965312985703349,
 0.005355127155780792,
 -0.0076866960152983665,
 -0.015173899941146374,
 -0.0029939464293420315,
 0.02464979514479637,
 -0.0012179953046143055,
 0.006714170332998037,
 -0.025472700595855713,
 0.026607314124703407,
 0.0124121755361557,
 0.007200433406978846,
 -0.0027227611280977726,
 -0.029699448496103287,
 0.0006004257593303919,
 -0.0012164368527010083,
 0.014974407851696014,
 0.021919241175055504,
 -0.02628313936293125,
 0.000322421983582899,
 -0.009326275438070297,
 -0.013652769848704338,
 -0.023914165794849396,
 0.011551863513886929,
 0.011028195731341839,
 -0.01834084279835224,
 -0.016857117414474487,
 -0.00870286114513874,
 0.022517718374729156,
 0.005277200601994991,
 0.015036748722195625,
 0.010392313823103905,
 -0.008858715184032917,
 0.031270451843738556,
 -0.023328157141804695,
 0.009937221184372902,
 0.006695467978715897,
 0.019550267606973648,
 -0.014326056465506554,
 0.009139250963926315,
 0.00020046660210937262,
 -0.026058711111545563,
 0.021819494664669037,
 -0.015460669994354248,
 -0.008709095418453217,
 -0.023602459579706192,
 0.01693192683160305,
 0.011782526969909668,
 0.025023842230439186,
 -0.021944178268313408,
 0.02160753309726715,
 0.00820412952452898,
 -0.011252624914050102,
 -0.024836819618940353,
 -0.013154038228094578,
 0.012424643151462078,
 -0.004491698928177357,
 0.013154038228094578,
 0.019126346334815025,
 -0.00013900187332183123,
 0.009320041164755821,
 0.001322417170740664,
 -0.008116851560771465,
 0.031095895916223526,
 -0.020460451021790504,
 -0.0003327472950331867,
 -0.00029612172511406243,
 0.012967013753950596,
 -0.003690611571073532,
 -0.017293507233262062,

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files

In [ ]:
uploaded = files.upload()
file = next(iter(uploaded))
data=pd.read_csv(file)

Saving words.csv to words.csv

In [ ]:
data

      text
0      red
1  potatos
2     soda
3   cheese
4    water
5     blue
6   cheese
7    green

In [ ]:
data['embeddings'] = data['text'].apply(lambda x: getEmbedding(x))
data

      text                                         embeddings
0      red  [9.326533472631127e-06, -0.02476814016699791, ...
1  potatos  [0.0002298674953635782, -0.031666286289691925,...
2     soda  [0.02577228657901287, -0.007436878979206085, -...
3   cheese  [-0.0032272646203637123, -0.008705058135092258...
4    water  [0.01912183128297329, -0.012477339245378971, 0...
5     blue  [0.005474964156746864, -0.007486246060580015, ...
6   cheese  [-0.0032272646203637123, -0.008705058135092258...
7    green  [0.01546180434525013, -0.010975971817970276, 0...

In [ ]:
data.to_csv("embeddings.csv")